[project]
name = "spotify-playlist-snapshot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyaml>=25.7.0",
    "spotipy>=2.25.2",
]
